#!/bin/bash
set -e

LFS_PART=$1
LFS=$2
REPO_ORIGIN_SOURCES=$3
DATADIR=$4
REPO_ORIGIN_PACKAGES_TMPSYS=$5
ROOT_REPO=$6
LFS_VER=$7

if [ ! -d "$2" ]
then
      mkdir $2
fi

echo ">>>Validacion de versiones $LFS_VER .."
if [ "$LFS_VER"="8.4" ]; then
	bdt-version-check-8.4
elif [ "$LFS_VER"="10.0" ]; then
	bdt-version-check-10.0
fi

echo ">>>Particionando disco.."
bdt-prephost-formatdisk $1 $2


echo ">>>Descargo paquetes.."
#bdt-prephost-download $3 

echo ">>>Preparando directorio de tools"
mkdir -v $2/tools
ln -sv $2/tools /

echo ">>>Creando usuario."
bdt-prephost-user $ROOT_REPO $LFS_VER $LFS

echo ">>>Moviendo archivos de trabajo."
mkdir $2/tools/sources
echo ">>>Validacion de versiones $LFS_VER .."
if [ "$LFS_VER"="8.4" ]; then
	cp -r $ROOT_REPO/sources/lfs/$LFS_VER/* $2/tools/sources/
	chmod -v a+wt $2/tools/sources/
	mkdir $2/tools/tmpsys
	cp -r $ROOT_REPO/packages/lfs/$LFS_VER/tmpsys/* $2/tools/tmpsys
	mkdir $2/tools/basic
	cp -r $ROOT_REPO/packages/lfs/$LFS_VER/basic/* $2/tools/basic

elif [ "$LFS_VER"="10.0" ]; then
	cp -r $REPO_ORIGIN_SOURCES/cross-toolchain/* $2/tools/sources/
	chmod -v a+wt $2/tools/sources/
fi



chown -v lfs $LFS/tools
chown -v lfs $LFS/tools/sources

mkdir -p $LFS/etc/pkmt
chown -v lfs $LFS/etc
chown -v lfs $LFS/etc/pkmt


echo ">>>Login in lfs"
su - lfs
echo "LFS=$LFS"
