#!/bin/bash
set -e

LFS_PART=$1
LFS=$2
REPO_ORIGIN_SOURCES=$3
DATADIR=$4
REPO_ORIGIN_PACKAGES_TMPSYS=$5

if [ ! -d "$2" ]
then
      mkdir $2
fi

echo ">>>Validacion de versiones.."
bdt-version-check

echo ">>>Particionando disco.."
echo ">>>Entrando en modo sudo.."
bdt-prephost-formatdisk $1 $2


echo ">>>Descargo paquetes.."
bdt-prephost-download $3

echo ">>>Preparando directorio de tools"
mkdir -v $2/tools
ln -sv $2/tools /

echo ">>>Creando usuario."
bdt-prephost-user $DATADIR

echo ">>>Moviendo archivos de trabajo."
mkdir $2/tools/sources
cp -r $REPO_ORIGIN_SOURCES/* $2/tools/sources/
mkdir $2/tools/tmpsys
cp -r $REPO_ORIGIN_PACKAGES_TMPSYS/* $2/tools/tmpsys


echo ">>>Login in lfs"
su - lfs

