#!/bin/bash
set -e


if [ ! -z "$(df | grep $1)" ]
then
    echo ">>>Desmontando $1."
    umount $1
fi

if [ ! -d "$2" ]
then
      rm -r $2
fi


if id "lfs" >/dev/null 2>&1; then
    	userdel lfs
fi
if grep -q "lfs" /etc/group; then
	groupdel lfs	
fi
if [ -d "/home/lfs" ] ;then
	rm -r /home/lfs
fi

if [ -L "/tools" ]
then
      	unlink /tools
fi
if [ -d "$2/tools" ]
then
      	rm -r $2/tools
fi
if [ -d "$2/sources" ]
then
      	rm -r $2/sources
fi
