#!/bin/bash
set -e

DATADIR=$1
ROOT_REPO=$2
LFS_VER=$3
LFS=$4

if id "lfs" >/dev/null 2>&1; then
	echo "El usuario 'lfs' ya existe."
    	exit
else
    groupadd lfs
    useradd -s /bin/bash -g lfs -m -k /dev/null lfs
    cp $ROOT_REPO/files/$LFS_VER/bash_profile /home/lfs/.bash_profile
    chown lfs:lfs /home/lfs/.bash_profile
    cp $ROOT_REPO/files/$LFS_VER/bashrc /home/lfs/.bashrc
    chown lfs:lfs /home/lfs/.bashrc
    echo "Introduca la contraseña para el numevo usuario 'lfs'"    
    passwd lfs
fi
